### ISSUE TITLE
gulp-browserify blacklisted

### ISSUE THREAD

**Issue by xsegrity** [BrowserSync/browser-sync-client#12]
I use browser-sync in my gulp files, which in turn uses browser-sync-client, which in turn is using the **blacklisted** and no longer maintained [gulp-browserify](https://github.com/deepak1556/gulp-browserify) package. Might think about removing that dependency. Here is a Gulp [recipe](https://github.com/gulpjs/gulp/blob/master/docs/recipes/browserify-uglify-sourcemap.md) showing how to use just plain browserify.

Hope that helps.

**Comment by shinnn** [comment]
Seems to be fixed in ef6ee997a714e838c5a1fc2f0fd909eddd9f4088
