### ISSUE TITLE
Unable to hide "Disconnected from BrowserSync" notification message

### ISSUE THREAD

**Issue by kirkov** [BrowserSync/browser-sync-client#18]
The "Disconnected from BrowserSync" notifiction is still displayed when `notify` option is set to `false`. Is this expected behavior ? 

The connected notification checks the property:

	if (options.notify) {
		notify.flash("Connected to BrowserSync");
	}

While the disconnected notification does not:

	socket.on("disconnect", function () {
		notify.flash("Disconnected from BrowserSync");
		shouldReload = true;
	});

According to the docs, `notify: false` should not show any notifictions:

    // Don't show any notifications in the browser.
    notify: false

**Comment by shakyShane** [comment]
Please run this to get the upstream fixes :)

```sh
npm rm browser-sync && npm install browser-sync@latest
```

**Comment by kirkov** [comment]
Awesome, thanks! :+1:
