### ISSUE TITLE
Extend notify styles instead of replacing

### ISSUE THREAD

**Issue by joemaller** [BrowserSync/browser-sync-client#26]
BrowserSync/browser-sync#685 shows how to override the styles on the in-browser notify div in [lib/notify.js](https://github.com/BrowserSync/browser-sync-client/blob/master/lib/notify.js#L36-L38), but changing any single rule requires replicating the entire styles array. 

It would be nice if we could override a single style rule. For example, only changing the background color, font-size or positioning.

Also, would it be ok to add a Lodash dependency to help streamline this?

**Comment by shakyShane** [comment]
If you're planning on implementing this, I'd say it's simple enough to not need an external lib. Just change from an array to an object and do a simple key loop?

**Comment by joemaller** [comment]
Yeah, the library request was just laziness. :sleeping: 

I spent a little extra time to make sure existing whole-array behavior still works if `options.notify.styles` is an array. If it gets an object, all properties of the object are merged onto the default styles object.  There are tests for both behaviors.

**Comment by shakyShane** [comment]
fixed via https://github.com/BrowserSync/browser-sync-client/pull/27
