### ISSUE TITLE
Unsubscribe event listeners when ghostmode is disabled

### ISSUE THREAD

**Issue by olegskl** [BrowserSync/browser-sync-client#35]
Even if we disable `ghostmode` the client continues to listen to events, including scroll. This becomes problematic when profiling application performance because browser-sync-client pollutes the frames and forces browsers to reflow content by reading `window.pageXOffset` and `window.pageYOffset`. See attached screenshot:

![browser-sync-client-profiling](https://cloud.githubusercontent.com/assets/298275/20925429/3a0d88e8-bbb7-11e6-8f19-e8bef02514fc.png)

Do you think it would be a good idea to subscribe/unsubscribe event listeners when changing options?

**Comment by shakyShane** [comment]
Fixed in browser-sync@2.18.5 - Thanks :)
